site_name: Pi-hole Add-on for Splunk Documentation
edit_uri: edit/master/docs/
repo_url: https://github.com/ZachChristensen28/TA-pihole_dns
repo_name: ZachChristensen28/TA-pihole_dns
site_description: >-
  Welcome to the Home of the Pi-hole Add-on for Splunk documentation. The Pi-hole Add-on allows Splunk data administrators to map the Pi-Hole® DNS server events to the CIM enabling the data to be used with other Splunk Apps, such as the Pihole App for Splunk.

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - def_list
  - footnotes
  - meta
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  logo: images/ph_ta_logo.png
  favicon: images/ph_ta_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - header.autohide
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - navigation.tracking
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zachary-christensen28/
    - icon: fontawesome/brands/github
      link: https://github.com/ZachChristensen28
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ZachTheSplunker

copyright: Copyright &copy; 2023 ZachTheSplunker

nav:
  - Home: index.md
  - Pi-hole Add-on: landing-page.md
  - Getting Started:
      - Pi-hole Logging Requirements: getting-started/pihole-logging-requirements.md
      - Where to Install: getting-started/where-to-install.md
      - Configure Inputs:
          - Configure Universal Forwarder: getting-started/configure-inputs/configure-inputs.md
          - Configure Modular Input: getting-started/configure-inputs/configure-modinput.md
      - Troubleshooting:
          - Troubleshoot Monitoring Inputs: getting-started/troubleshooting/troubleshoot-inputs.md
          - Troubleshoot Modular Input: getting-started/troubleshooting/troubleshoot-modinputs.md
  - Reference:
      - Sourectypes: reference/sourcetypes.md
      - Modular Input Reference: reference/mod-input-reference.md
      - Changelog:
          - Release Notes: reference/releases/index.md
          - Release History: reference/releases/release-history.md
      - Third-party software:
          - Credits: reference/credits.md
