name: Increment Build caller

on:
  push:
    branches:
      - devel
      - development
    paths:
      - "src/**"
      - "!app.conf"

jobs:
  call-packaging-workflow:
    uses: ZachChristensen28/splunk-github-wfa/.github/workflows/increment-build-number.yml@main
